name: Testing

on: pull_request

jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: rolling
          import-token: ${{ secrets.REPO_TOKEN }}
          package-name:
            composition_benchmark
            irobot_benchmark
            irobot_interfaces_plugin
            performance_metrics
            performance_test
            performance_test_examples
            performance_test_factory
            performance_test_msgs
            performance_test_plugin_cmake
